name: Github CI
on: push

jobs:
  build:
    name: Build DockerImage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Docker
        run: |
          uname -a
          sudo apt-get remove docker docker-engine docker.io containerd runc -y
          sudo apt update -y
          sudo apt-get install \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
          sudo apt-get update -y
          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
          docker version
      - name: Build Dockerfile
        run: |
          docker build --build-arg ROLE=master   -t registry.cn-hangzhou.aliyuncs.com/geekcloud/hound:master  .
          docker build --build-arg ROLE=agent   -t registry.cn-hangzhou.aliyuncs.com/geekcloud/hound:agent  .
      - name: Push Images
        env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
        run: |
          echo $password | sudo docker login "registry.cn-hangzhou.aliyuncs.com" -u "$username" --password-stdin
          docker push registry.cn-hangzhou.aliyuncs.com/geekcloud/hound:master
          docker push registry.cn-hangzhou.aliyuncs.com/geekcloud/hound:agent
          docker logout